### ISSUE TITLE
Compile instructions are sparse. They dont mention which version of visual studio is required.

### ISSUE THREAD

**Issue by jamesjcook** [Rychard/GnomeServer#15]
It would help to note compiling is known functional with visual studio 2015. I tested with 2015 community edition and it worked. It didnt work with Visual studio 2008 express or 2012.

**Comment by Rychard** [comment]
Good catch!  I've made a quick edit to the `README` to mention the requirement of Visual Studio 2015.  

Thanks for bringing this to my attention!
